from .auth import router
from .suppliers import router
from .products import router
from .warehouses import router
from .inventory import router
from .customers import router
from .orders import router
from .shipments import router
from .logistics import router
from .tracking import router
